backend:
  name: github
  repo:EaGlEtSuImars/EaGlEtSuImars.github.io
  branch: main   # or 'master' if that's your default

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "_posts/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "members"
    label: "Members"
    folder: "_members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image", required: false}
      - {label: "Bio", name: "body", widget: "markdown", required: false}
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Project Link", name: "link", widget: "string", required: false}
